CREATE TABLE IF NOT EXISTS cases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  reference VARCHAR(255) NOT NULL UNIQUE,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(2000),

  status VARCHAR(255) NOT NULL,
  outcome VARCHAR(255) NOT NULL,

  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,

  last_change_reason VARCHAR(300),
  deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_cases_deleted_at ON cases (deleted_at);
CREATE INDEX IF NOT EXISTS idx_cases_created_at ON cases (created_at);